version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php_app
    volumes:
      - ./php:/var/www/html/
      - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: preorderpal
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
